# STAGES

stages:
  - validate
  - code_style

variables:
  DANGER_GITLAB_HOST: "git.epam.com"
  DANGER_GITLAB_API_BASE_URL: "https://git.epam.com/api/v4"
  CHECKSTYLE_THRESHOLD: 5

# STAGE: validate

Validate:
  image: maven:3.6.3-openjdk-14
  stage: validate
  script:
    - mvn validate
  only:
    - master

Compile:
  image: maven:3.6.3-openjdk-14
  stage: validate
  script:
    - mvn compile
  only:
    - master

# STAGE: code_style

Checkstyle:
  image: maven:3.6.3-openjdk-14
  stage: code_style
  script:
    - mvn checkstyle:check -Dcheckstyle.maxAllowedViolations=$CHECKSTYLE_THRESHOLD
  only:
    - master